name: Deploy Laravel
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Jalankan Deploy Script di Fedora
        run: |
          # 1. Pindah ke folder project di /var/www/
          cd /var/www/gitlab-laravel || exit
          
          # 2. Tarik kode terbaru
          git pull origin main
          
          # 3. Install dependencies & migrasi
          composer install --no-dev
          php artisan migrate --force
          
          # 4. Optimasi (Penting untuk Laravel di Production/Nginx)
          php artisan config:cache
          php artisan route:cache
          
          # 5. Pastikan permission tetap aman (Opsional tapi disarankan)
          sudo chmod -R 775 storage bootstrap/cache