name: Deploy Laravel
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Jalankan Deploy Script di Fedora
        run: |
          # 1. Pindah ke folder project
          cd /var/www/gitlab-laravel || exit
          
          # 2. Tarik kode terbaru
          git pull origin main
          
          # 3. Install dependencies & migrasi
          composer install --no-dev
          php artisan migrate --force
          
          # 4. Optimasi Laravel
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
          
          # 5. Permission (HAPUS SUDO)
          # Karena folder ini milik user chnoxi, kita tidak butuh sudo untuk chmod
          chmod -R 775 storage bootstrap/cache