name: Deploy Laravel
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      
      - name: Jalankan Deploy Script Lokal
        run: |
          # Perintah ini akan dijalankan langsung di Fedora kamu
          cd /var/www/html/gitlab-laravel || exit
          git pull origin main
          composer install --no-dev
          php artisan migrate --force